services:
  db:
    restart: always
    image: postgres:14-alpine
    container_name: 'mastodon-db'
    shm_size: 256mb
    networks:
      - default
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    command: postgres -c 'max_connections=150'

  redis:
    restart: always
    image: redis:7-alpine
    container_name: 'mastodon-redis'
    networks:
      - default
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./redis:/data

  #  es:
  #    restart: unless-stopped
  #    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
  #    container_name: "mastodon-es"
  #    environment:
  #      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true"
  #      - "xpack.license.self_generated.type=basic"
  #      - "xpack.security.enabled=false"
  #      - "xpack.watcher.enabled=false"
  #      - "xpack.graph.enabled=false"
  #      - "xpack.ml.enabled=false"
  #      - "bootstrap.memory_lock=true"
  #      - "cluster.name=mastodon-es"
  #      - "discovery.type=single-node"
  #      - "thread_pool.write.queue_size=1000"
  #    networks:
  #      - proxy
  #      - default
  #    healthcheck:
  #       test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
  #    volumes:
  #       - ./esearch:/usr/share/elasticsearch/data
  #    ulimits:
  #      memlock:
  #        soft: -1
  #        hard: -1
  #      nofile:
  #        soft: 65536
  #        hard: 65536

  console:
    image: ghcr.io/mastodon/mastodon:v4.5.0
    container_name: 'mastodon-console'
    env_file: .env.production
    command: /bin/bash
    restart: 'no'
    depends_on:
      - redis
    networks:
      - default
      - proxy
    volumes:
      - /data/mastodon/public/system:/mastodon/public/system

  web:
    image: ghcr.io/mastodon/mastodon:v4.5.0
    restart: always
    container_name: 'mastodon-web'
    env_file: .env.production
    command: bundle exec puma -C config/puma.rb
    environment:
      - WEB_CONCURRENCY=5
      - MAX_THREADS=10
    networks:
      - default
      - proxy
    ports:
      - '3000:3000'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "curl -s --noproxy localhost localhost:3000/health | grep -q 'OK' || exit 1",
        ]
    depends_on:
      - db
      - redis
      - es
    volumes:
      - /data/mastodon/public/system:/mastodon/public/system
      - /data/mastodon/public/robots.txt:/mastodon/public/robots.txt:ro

  streaming:
    image: ghcr.io/mastodon/mastodon-streaming:v4.5.0
    restart: always
    container_name: 'mastodon-streaming'
    env_file: .env.production
    environment:
      - DB_POOL=50
    command: node ./streaming/index.js
    networks:
      - proxy
      - default
    ports:
      - '4000:4000'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "curl -s --noproxy localhost localhost:4000/api/v1/streaming/health | grep -q 'OK' || exit 1",
        ]
    depends_on:
      - db
      - redis

  sidekiq:
    image: ghcr.io/mastodon/mastodon:v4.5.0
    restart: always
    container_name: 'mastodon-sidekiq'
    env_file: .env.production
    environment:
      - DB_POOL=50
    command: bundle exec sidekiq -c 50
    depends_on:
      - db
      - redis
    networks:
      - proxy
      - default
    volumes:
      - /data/mastodon/public/system:/mastodon/public/system
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 8' || false"]
    ports:
      - '127.0.0.1:9200:9200'

networks:
  proxy:
  default:
    internal: true
